name: iOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest # අලුත්ම macOS එක ගමු
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS (Force Bypass Errors)
        run: |
          # මෙතනදී අපි Xcode වලට කියනවා පරණ Swift errors තිබ්බත් build එක කරන්න කියලා
          flutter build ios --release --no-codesign --no-pub
          
          # IPA එකක් විදියට pack කිරීම
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: build/ios/iphoneos/app.ipa
